name: .NET Test Workflow

on:
  push:
    branches:
      - main  # Detta triggar workflow när det görs en push till main-grenen

jobs:
  test:
    runs-on: ubuntu-latest  # Körs på en Ubuntu-latest-miljö

    steps:
      # Steg 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2  # Se till att repositoryt klonas korrekt

      # Steg 2: Setup .NET (med den senaste versionen)
      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'  # Använder .NET 7.0, som är under support

      # Steg 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Steg 4: Run unit tests
      - name: Run tests
        run: dotnet test
