name: .NET Test Workflow

on:
  push:
    branches:
      - main  # Triggas när det görs en push till main-grenen

jobs:
  test:
    runs-on: ubuntu-latest  # Körs på en Ubuntu-latest-miljö

    steps:
      # Steg 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2  # Bytte till v2 för att säkerställa stabilitet

      # Steg 2: Verifiera Git status
      - name: Git Status
        run: |
          git status
          git remote -v  # Kolla att rätt fjärrrepository är konfigurerat

      # Steg 3: Setup .NET 8.0
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Använder .NET 8.0

      # Steg 4: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Steg 5: Run tests
      - name: Run tests
        run: dotnet test

