name: .NET Test Workflow

on:
  push:
    branches:
      - main  # Triggas när det görs en push till main-grenen

jobs:
  test:
    runs-on: ubuntu-latest  # Körs på en Ubuntu-latest-miljö

    steps:
      # Steg 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3  # Uppdaterad version av checkout-action för bättre stabilitet

      # Steg 2: Setup .NET 8.0
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3  # Använder senaste versionen av .NET
        with:
          dotnet-version: '8.0'  # Uppdaterad till .NET 8.0

      # Steg 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Steg 4: Run tests
      - name: Run tests
        run: dotnet test
